### ISSUE TITLE
onEndReach not working properly

### ISSUE THREAD

**Issue by enahum** [jevakallio/react-native-reversed-flat-list#3]
So this is definitely rendering the list in the right order and scrolling from the bottom up but then things like onEndReach do not work as expected.

I would expect that when I get near the top of the list then onEndReach gets triggered. any thoughts?

**Comment by jevakallio** [comment]
Thanks for reporting this! I can reproduce the problem - onEndReached fires when the list is first scrolled in its visual "bottom" position, whereas you'd expect it to fire near the top.

I don't currently have time to figure out how to fix this. I added this as a known issue in the Readme - in the meantime, contributions welcome.

**Comment by rahmatkruniawan** [comment]
@jevakallio  are you still working on this issue?

**Comment by jevakallio** [comment]
@rahmatkruniawan it appears that React Native FlatList now supports inverted FlatLists natively using the `inverted` prop: https://facebook.github.io/react-native/docs/flatlist.html#inverted

As such I'm going to deprecate this component and suggest you use the underlying implementation.
