### ISSUE TITLE
Attribution incorrect

### ISSUE THREAD

**Issue by jeremyong** [jevakallio/react-native-reversed-flat-list#4]
Just mentioning it as a matter that's not super important (something I happened to know since I was a previous user of invertible scroll view). The commit you point to as attributing the scale transform is just a refactor. The usage of double inversion dates all the way back to the beginning: https://github.com/expo/react-native-invertible-scroll-view/commit/b0f1573637f516e6483754ddf12971187c1855d4

**Comment by jevakallio** [comment]
Hah, thanks! I did know about Charlie's matrix-based transform, but considered that (maybe too pedantically) a different technique from the `scaleY` transform.

In any case, React Native FlatList now supports reversed rendering out of the box using the **inverted** prop:

```js
  <FlatList inverted {...} />
```

As such, this component is now deprecated.
