### ISSUE TITLE
onRefresh does not working

### ISSUE THREAD

**Issue by kholiavko-roman** [jevakallio/react-native-reversed-flat-list#5]
Property 'onRefresh' does not working.
Here is my example:
```
<ReversedFlatList
    data={this.state.messages}
    keyExtractor={(item, index) => `id_${index}`}
    renderItem={this.renderItem.bind(this)}
    onRefresh={() => alert('123')}
    refreshing={false}
/>
```

**Comment by jevakallio** [comment]
React Native FlatList now supports reversed rendering out of the box using the **inverted** prop:

```js
  <FlatList inverted {...} />
```

As such, this component is no longer necessary. I recommend using the built in functionality instead.

**Comment by kholiavko-roman** [comment]
Thanks!
